---
###################################################################################################
## Description: This playbook will execute postchanges on elasticsearch and kibana on els cluster
## OS Dependency: RHEL 7.x
## Playbook Dependency: None
## Role Dependency: None
#####################################################################################################
- name: replace Xms2g to Xms10g  /etc/elasticsearch/jvm.options
  replace: path=/etc/elasticsearch/jvm.options regexp=Xms2g replace=Xms10g  owner=root group=root mode=660
 
- name: replace Xmx2g to Xmx10g /etc/elasticsearch/jvm.options
  replace: path=/etc/elasticsearch/jvm.options regexp=Xmx2g replace=Xmx10g backup=yes owner=root group=elasticsearch mode=660

- name: uncomment MAX_LOCKED_MEMORY in/etc/sysconfig/elasticsearch
  lineinfile: path=/etc/sysconfig/elasticsearch  regexp="^#MAX_LOCKED_MEMORY/s" line="MAX_LOCKED_MEMORY=unlimited" backup=yes owner=root group=root mode=660

- name: uncomment LimitMEMLOCK in /usr/lib/systemd/system/elasticsearch.service
  lineinfile: path=/usr/lib/systemd/system/elasticsearch.service regexp="^#LimitMEMLOCK=infinity" line="LimitMEMLOCK=infinity" backup=yes owner=root group=root mode=660

- name: add lines in /etc/elasticsearch/log4j2.properties
  lineinfile: path=/etc/elasticsearch/log4j2.properties insertbefore=EOF backup=yes owner=root group=elasticsearch mode=660
    line="logger.authc.name = org.elasticsearch.xpack.security.authc\nlogger.authc.level = INFO"

- name: remove index from /etc/elasticsearch/elasticsearch.yml
  replace: path=/etc/elasticsearch/elasticsearch.yml regexp="index, logfile" replace="logfile" backup=yes owner=root group=elasticsearch mode=660


- name: Install s3 repository pluggin
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
  ignore_errors: yes


- name: Disable elastic repo
  replace: path=/etc/yum.repos.d/elasticsearch.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: Disable kibana.repo
  replace: path=/etc/yum.repos.d/kibana.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: Disable logstash repo
  replace: path=/etc/yum.repos.d/logstash.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: Disable epel-repo
  replace: path=/etc/yum.repos.d/epel.repo regexp="enabled=1" replace="enabled=0" backup=yes

- name: Run yum clean all
  shell: yum clean all
